### ISSUE TITLE
1.12-1.82pr5 crashes dedicated server Forge 1.12 build 2382

### ISSUE THREAD

**Issue by kreezxil** [NoMansMinecraft/Computality#15]
Notes:
     on startup, something to do with forge registry

crash report:
https://gist.github.com/214d20a50e8d242cc45f7a652393b905

fml server latest:
https://gist.github.com/2102b4480092bb81413f5ccc3a1851ec

**Comment by TheCodedOne** [comment]
I'm currently rewriting computality for 1.12 so there will be no updates for the computercraft fork version of computality from this point on, in 1.12 if you wish to use computality you need to wait for the rewrite to be complete
