### ISSUE TITLE
redstone.setOutput() doesn't provide redstone update

### ISSUE THREAD

**Issue by Trevader24135** [NoMansMinecraft/Computality#18]
whenever redstone.setOutput() (or any other redstone command for that matter) is called to set true or false, on any side, it doesn't provide a redstone update to the surrounding redstone devices, so it stays in it's previous state until manually updated.

**Comment by TheCodedOne** [comment]
This is something i really need to prioritise fixing

**Comment by TheCodedOne** [comment]
Fixed in dev

**Comment by bowmanjd** [comment]
I would love to build this fix into the mod for 1.11.2. Which branch to I checkout for that? Or were you already planning to release a new 1.11.2 version? Thanks!

**Comment by TheCodedOne** [comment]
The redstone fix was never done for 1.11, there is no branch with that fix for 1.11

**Comment by bowmanjd** [comment]
Nuts. Ok, thanks for letting me know, and thanks for your good work on this mod.

**Comment by mfrojd** [comment]
Hello, I just wanted to touch base to see if there is any other solution to this issue. To easily relay what was said above is: A computer used to output a redstone response. The code can be redstone.setOutput("string",(true or false)) and the side the string says should update, however one must break that wire and replace it for the that block to receive the signal. Is there a way around this?
