### ISSUE TITLE
1.11.2-1.81

### ISSUE THREAD

**Issue by kreezxil** [NoMansMinecraft/Computality#2]
you can craft the mining mining turtle, but not the mining turtle.

**Comment by TheCodedOne** [comment]
i've been meaning to rewrite all the recipes, this is probably a good excuse to do so

**Comment by kreezxil** [comment]
Sweet. Food for thought consider making a programming repository and
including commands to search and install from it via the OS. you could
monetize write ads.

I like your port mainly because my programs still work in it.

**Comment by TheCodedOne** [comment]
that is something i am actually working on, also turtle upgrades are fixed and uploading the bug fix to curse now.

**Comment by TheCodedOne** [comment]
https://minecraft.curseforge.com/projects/computality/files/2418109
