### ISSUE TITLE
Cannot connect to Immersive Engineering machines

### ISSUE THREAD

**Issue by poeticbulldozer** [NoMansMinecraft/Computality#27]
I'm apologize if I'm just doing something completely boneheaded, but I suspect there is some trouble connecting Computality computers to Immersive Engineering machines using the API that IE provides. I have tried with modems, as well as connecting the computer directly to the machines. It seems to recognize energy storage devices, not no other machines. I'm unsure whether the problem lies with IE, Computality, or my own error, but I am happy to do some testing if you'd like me to come up with any details in particular.

**Comment by TheCodedOne** [comment]
Computality adds its own system for energy storage devices thats why they show up, so the problem probably is IE doesnt have support anymore, nothing i can do unless you can prove its an issue caused by computality which it doesnt seem to be
