### ISSUE TITLE
1.11.2-1.82pr1

### ISSUE THREAD

**Issue by kreezxil** [NoMansMinecraft/Computality#3]
Crash while using a turtle to build a mob farm using a mobfarm building program. It crashed the server and not the clients.

https://gist.github.com/08d4cfa62c22aa26679481daef21da8e

I think the turtle might've tried to dig through reinforced stone not quite sure. Gonna try again.

**Comment by kreezxil** [comment]
also, I noticed that ctrl+c doesn't work on the os screen

**Comment by kreezxil** [comment]
probably the same thing, it's happened like 4 times now. I thought it was something specific but it is happening random on placing blocks, doesn't appear to be a rhyme or a reason. The additional 3 server crash reports.

1. https://gist.github.com/310d507a885d51fc6f1784561cc836f8
1. https://gist.github.com/57328f617f7f037e042479aa2ec24ed9
1. https://gist.github.com/cb175e73915c0df1ee5cfdfc0913d20a

also fml-server logs

1. https://gist.github.com/e598626f069f5736dd9fe7af9ccda379
1. https://gist.github.com/deb569661942d026247ac7b5f5baf282
1. https://gist.github.com/a9c9b268f4f9a9c76cd5bb91a84437bd

fml server latest: 
https://gist.github.com/1e9d568fed3db59ee45844ea7a02f592

**Comment by TheCodedOne** [comment]
hm..

**Comment by TheCodedOne** [comment]
i am unable to replicate

**Comment by TheCodedOne** [comment]
also ctrl+c isn't a valid shortcut, 

- ctrl+t terminate
- ctrl+r reboot
- ctrl+s shutdown

Computality does add
- ctrl+x terminate along side ctrl+t

i may consider adding ctrl+c as well

**Comment by kreezxil** [comment]
lol, I've been away from computercraft so long that I forgot about those others. Testing the fix shortly.

**Comment by kreezxil** [comment]
Good news it works!!!
