### ISSUE TITLE
Computality keeps crashing after several attempts

### ISSUE THREAD

**Issue by mshivalkar** [NoMansMinecraft/Computality#31]
My son had been to the programming camp where they used ComputerCraft. I think Computality is the fork of ComputerCraft for Minecraft 1.11 and greater so I started installing it for him but no luck. here is the detail with the versions I have of everything... PLEASE HELP.

Minecraft 1.12
forge-1.12-14.21.1.2424
NMMLib-1.0.4
Computality-Mod-1.12
 
The crash report says:
---- Minecraft Crash Report -------- Minecraft Crash Report ----
WARNING: coremods are present:Contact their authors BEFORE contacting forge
// Surprise! Haha. Well, this is awkward.
Time: 7/25/17 2:30 PMDescription: There was a severe problem during mod loading that has caused the game to fail
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Computality (computercraft)Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:344) at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85) at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:591) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252) at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) at com.google.common.eventbus.EventBus.post(EventBus.java:217) at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147) at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570) at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.IForgeRegistryEntry at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ... 40 moreCaused by: java.lang.NullPointerException
A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- System Details --Details: Minecraft Version: 1.12 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_25, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 120526360 bytes (114 MB) / 336830464 bytes (321 MB) up to 1060372480 bytes (1011 MB) JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP 9.40 Powered by Forge 14.21.1.2424 Optifine OptiFine_1.12_HD_U_C4 6 mods loaded, 6 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored UC minecraft{1.12} [Minecraft] (minecraft.jar)  UC mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)  UC FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2424.jar)  UC forge{14.21.1.2424} [Minecraft Forge] (forge-1.12-14.21.1.2424.jar)  UC nmmlib{1.0.0} [NoMansLib] (NMMLib-1.0.4.jar)  UE computercraft{1.12-1.82pr5} [Computality] (Computality-Mod-1.12.jar)  Loaded coremods (and transformers):  GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000' OptiFine Version: OptiFine_1.12_HD_U_C4 Render Distance Chunks: 12 Mipmaps: 4 Anisotropic Filtering: 1 Antialiasing: 0 Multitexture: false Shaders: null OpenGlVersion: 4.0.0 - Build 10.18.10.4358 OpenGlRenderer: Intel(R) HD Graphics 4000 OpenGlVendor: Intel CpuCount: 4
 
I wanted to provide additional information from fml_client_latest log. 
 
The crash happens during the transition from CONSTRUCTING to PREINITIALIZATION.
 
[14:30:26] [main/DEBUG] [FML/]: Bar Finished: Construction took 1.012s[14:30:26] [main/DEBUG] [FML/]: Bar Finished: Construction took 1.012s[14:30:26] [main/DEBUG] [FML/]: Mod signature data[14:30:26] [main/DEBUG] [FML/]:   Valid Signatures:[14:30:26] [main/DEBUG] [FML/]: (e3c3d50c7c986df74c645c0ac54639741c90a557) FML (Forge Mod Loader 8.0.99.99) forge-1.12-14.21.1.2424.jar[14:30:26] [main/DEBUG] [FML/]: (e3c3d50c7c986df74c645c0ac54639741c90a557) forge (Minecraft Forge 14.21.1.2424) forge-1.12-14.21.1.2424.jar[14:30:26] [main/DEBUG] [FML/]:   Missing Signatures:[14:30:26] [main/DEBUG] [FML/]: minecraft (Minecraft 1.12) minecraft.jar[14:30:26] [main/DEBUG] [FML/]: mcp (Minecraft Coder Pack 9.19) minecraft.jar[14:30:26] [main/DEBUG] [FML/]: nmmlib (NoMansLib 1.0.0) NMMLib-1.0.4.jar[14:30:26] [main/DEBUG] [FML/]: computercraft (Computality 1.12-1.82pr5) Computality-Mod-1.12.jar[14:30:26] [main/FATAL] [FML/]: Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue[14:30:26] [main/FATAL] [FML/]:  States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored UC minecraft{1.12} [Minecraft] (minecraft.jar)  UC mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)  UC FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2424.jar)  UC forge{14.21.1.2424} [Minecraft Forge] (forge-1.12-14.21.1.2424.jar)  UC nmmlib{1.0.0} [NoMansLib] (NMMLib-1.0.4.jar)  UE computercraft{1.12-1.82pr5} [Computality] (Computality-Mod-1.12.jar) [14:30:26] [main/FATAL] [FML/]: The following problems were captured during this phase[14:30:26] [main/ERROR] [FML/]: Caught exception from computercraft (java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry)

**Comment by TheCodedOne** [comment]
You're trying to use 1.12 but i have no 1.12 version released on curse, use 1.11 and that'll fix your issue

**Comment by mshivalkar** [comment]
Thank you very much. It’s all working now. Appreciate quick response.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
