### ISSUE TITLE
[1.12] Computers just not working

### ISSUE THREAD

**Issue by Skillotic0703** [NoMansMinecraft/Computality#34]
Minecraft version : 1.12
Computality version : 1.12-1.82.2
Forge version : 1.12 - 14.21.1.2443
Computality is the only mod that I'm using. I created a void world to test things. I took a computer in the creative menu. I right-clicked the computer and I just have a black screen. I can't write anything. It also happens with the advanced computer. I can't use the shortcut to restart the computer either.

**Comment by Skillotic0703** [comment]
It also happens with turtles (any terminal)

**Comment by TheCodedOne** [comment]
Are there any errors in console?

**Comment by Skillotic0703** [comment]
No nothing is written, there is just a black screen

**Comment by TheCodedOne** [comment]
i mean in game console, not the computer screen

**Comment by Skillotic0703** [comment]
The logs?

**Comment by TheCodedOne** [comment]
yes

**Comment by Skillotic0703** [comment]
https://pastebin.com/4h2sGS4t

**Comment by TheCodedOne** [comment]
Fixed in dev, will put a bug fix out soon

**Comment by Skillotic0703** [comment]
Thank you!
