### ISSUE TITLE
[1.12] Blocks have a wrong texture in the inventory and in-hand

### ISSUE THREAD

**Issue by Skillotic0703** [NoMansMinecraft/Computality#35]
Minecraft version : 1.12
Computality version : 1.12-1.82.2
Forge version : 1.12 - 14.21.1.2443
![2017-08-11_15 07 18](https://user-images.githubusercontent.com/12701912/29214220-ca45bff4-7ea6-11e7-9897-3976365610d3.png)

**Comment by TheCodedOne** [comment]
Thats a very strange bug, i'll see if i can see why its happening

**Comment by TheCodedOne** [comment]
is it just peripherals or are all blocks showing the wrong icon?

**Comment by Skillotic0703** [comment]
I think this is just peripherals

**Comment by TheCodedOne** [comment]
Fixed in dev ![image](https://user-images.githubusercontent.com/17037059/29215249-28b67542-7ea2-11e7-9991-727bdfbd45fd.png)
