### ISSUE TITLE
Crash on Turtel Fuel with Coal

### ISSUE THREAD

**Issue by m00nLP** [NoMansMinecraft/Computality#5]
Hey guys
My client crashed with coal fuel for Mining Turtle
http://www.m00nlp.de/download/crash.txt

**Comment by m00nLP** [comment]
Hello?

**Comment by m00nLP** [comment]
Its a bug okay! and now?

**Comment by m00nLP** [comment]
Hey how long must i wait here for fix this bug i need this mod

**Comment by TheCodedOne** [comment]
long enough, i have other things to do i cant fix things instantly on unsupported versions

**Comment by TheCodedOne** [comment]
1.10 is unsupported, i wont be doing any fixes for this version
