### ISSUE TITLE
Turtles bypass claims

### ISSUE THREAD

**Issue by OrdinatorStouff** [NoMansMinecraft/Computality#6]
The ability for a turtle to be programmed to 1) enter and then 2) break/place inside an FTBU claim is something that should be addressed. I understand the "fakeUser" option of FTBU protection can be disabled but that still doesn't stop turtles from entering, and secondly a user shouldn't be forced to decide between automation placer/breaker setups or protection from rogue turtles.

Is this something that should be addressed in Computality code or should it be addressed by FTBU's code? Or both?

**Comment by TheCodedOne** [comment]
Fixed in latest release
